version: '3.4'

services:
  app:
    image: letsquiz-app-image
    container_name: letsquiz-app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    links:
      - "db:letsquiz-db"
  db:
    image: letsquiz-db-image
    container_name: letsquiz-db
    build:
      context: ./db
      dockerfile: Dockerfile
